### PR TITLE
Bump Packages.

### PR DESCRIPTION
**Pull request by camrun91**
This bumps the packages to the latest release of v2. This should take care of some of the android issues they are seeing.

### CODE REVIEW

**Comment by redreceipt** [comment]
assuming you booted the sim with no issues?

**Comment by camrun91** [comment]
The login screen was the big one. I Will look at that issue and see if I can replicate it. It is likely somewhere I missed putting in the change.

**Comment by redreceipt** [comment]
@nlewis84 is that the current behavior of the galaxy nexus even without the PR?

**Review by redreceipt — APPROVED** [review]

**Comment by camrun91** [comment]
> ![2022-03-29 09 54 08]
> 
> Check this out @camrun91. Galaxy Nexus. This was after pulling down this PR and `yarn`

That is odd it also looks like those second screens have a bigger header too. 
I am creating a sim with a smaller device to see if I can replicate.

**Comment by nlewis84** [comment]
@redreceipt No, it's different and way worse without @camrun91's fixes 😆

**Comment by camrun91** [comment]
@conrad-vanl @redreceipt @nlewis84 OK we probably need to decide what is "expected functionality here" the changes I made work well on the bigger devices, but when I test on a smaller device we get the same scrolling effect.

**Comment by conrad-vanl** [comment]
@camrun91 I am not familiar enough with android to understand expected behavior for smaller screens. Can you record a demo of what happens?

Also, can you play around with any other apps on this android device and see if there's some patterns you are seeing that we might be able to follow?

**Pull request merged**
